if ($ENV{VECGEOM_DIR})
  set(VECGEOM_DIR $ENV{VECGEOM_DIR})
endif()

if (NOT USOLIDS_DIR)
  if (EXISTS ${PROJECT_SOURCE_DIR}/../base/Global.h)
    set(VECGEOM_DIR ${PROJECT_SOURCE_DIR}/..)
    set(VECGEOM_INCLUDE_DIR ${VECGEOM_DIR})
  else()
    message(ERROR "VecGeom project could not be located. Try to set a VECGEOM_DIR environment variable to the base installation path or add -DVECGEOM_DIR to the cmake command")
  endif()
else()
  set(VECGEOM_INCLUDE_DIR ${VECGEOM_DIR})
endif()
