if ($ENV{USOLIDS_DIR})
  set(USOLIDS_DIR $ENV{USOLIDS_DIR})
endif()

if (NOT USOLIDS_DIR)
  message(STATUS "Building with embedded USolids.")
  set(USOLIDS_EMBEDDED TRUE)
  set(USOLIDS_DIR ${PROJECT_SOURCE_DIR}/USolids)
  set(USOLIDS_LIB_DIR ${CMAKE_BINARY_DIR}/USolids/lib)
  set(USOLIDS_INCLUDE_DIR ${USOLIDS_DIR}/include)
  set(USOLIDS_LIBRARIES USolids)
else()
  message(STATUS "Building with existing USolids.")
  set(USOLIDS_EMBEDDED FALSE)
  set(USOLIDS_INCLUDE_DIR ${USOLIDS_DIR}/include)
  set(USOLIDS_LIB_DIR ${USOLIDS_DIR}/lib)
  find_library(USOLIDS_LIBRARIES USolids PATHS "${USOLIDS_LIB_DIR}" NO_DEFAULT_PATH)
  if (USOLIDS_LIBRARIES)
    set (USOLIDS_FOUND TRUE)
    get_filename_component(_USOLIDS_LIBRARIES_WE ${USOLIDS_LIBRARIES} NAME)
    get_filename_component(_USOLIDS_LIBRARIES_DIRECTORY ${USOLIDS_LIBRARIES} PATH)
    message(STATUS "Found USolids library ${_USOLIDS_LIBRARIES_WE} in ${_USOLIDS_LIBRARIES_DIRECTORY}")
  else()
    message(STATUS "USolids library not found; try to set a USOLIDS_DIR environment variable to the base installation path or add -DUSOLIDS_DIR to the cmake command")
  endif()
endif()
