if ($ENV{USOLIDS_DIR})
  set(USOLIDS_DIR $ENV{USOLIDS_DIR})
endif()

if (NOT USOLIDS_DIR)
  message(STATUS "Building with shipped USolids.")
  set(USOLIDS_DIR ${PROJECT_SOURCE_DIR}/USolids)
  add_subdirectory(${USOLIDS_DIR})
  set (USOLIDS_INCLUDE_DIR ${USOLIDS_DIR}/include)
  set (USOLIDS_LIB_DIRS ${USOLIDS_DIR}/lib)
  set (USOLIDS_LIBRARIES ${USOLIDS_LIB_DIR}/libusolids.a)
else()
  set (USOLIDS_INCLUDE_DIR ${USOLIDS_DIR}/include)
  set (USOLIDS_LIB_DIRS ${USOLIDS_DIR}/lib)
  find_library(USOLIDS_LIBRARIES usolids PATHS "${USOLIDS_LIB_DIR}" NO_DEFAULT_PATH)
  if (USOLIDS_LIBRARIES)
    set(USOLIDS_FOUND TRUE)
    message(STATUS "Found USolids library ${USOLIDS_LIBRARIES} in ${USOLIDS_LIB_DIR}")
  else()
    message(STATUS "USolids library not found; try to set a USOLIDS_DIR environment variable to the base installation path or add -DUSOLIDS_DIR to the cmake command")
  endif()
endif()
