if ($ENV{CMSGeom_DIR})
  set(CMSGeom_DIR $ENV{CMSGeom_DIR})
endif()

if (NOT CMSGeom_DIR)
  message(STATUS "Building with embedded CMSGeom.")
  set(CMSGEOM_EMBEDDED TRUE)
  set(CMSGEOM_DIR ${PROJECT_SOURCE_DIR}/CMSGeom)
  set(CMSGEOM_INCLUDE_DIR ${CMSGEOM_DIR}/include)
  set(CMSGEOM_LIB_DIR ${CMAKE_BINARY_DIR}/CMSGeom/lib)
  set(CMSGEOM_LIBRARIES CMSGeom)
else()
  message(STATUS "Building with existing CMSGeom.")
  set(CMSGEOM_EMBEDDED FALSE)
  set(CMSGEOM_INCLUDE_DIR ${CMSGEOM_DIR}/include)
  set(CMSGEOM_LIB_DIR ${CMSGEOM_DIR}/lib)
  find_library(CMSGEOM_LIBRARIES CMSGeom PATHS "${CMSGEOM_LIB_DIR}" NO_DEFAULT_PATH)
  if (CMSGEOM_LIBRARIES)
    set (CMSGEOM_FOUND TRUE)
    get_filename_component(_CMSGEOM_LIBRARIES_WE ${CMSGEOM_LIBRARIES} NAME)
    get_filename_component(_CMSGEOM_LIBRARIES_DIRECTORY ${CMSGEOM_LIBRARIES} PATH)
    message(STATUS "Found CMSGeom library ${_CMSGEOM_LIBRARIES_WE} in ${_CMSGEOM_LIBRARIES_DIRECTORY}")
  else()
    message(STATUS "CMSGeom library not found; try to set a CMSGeom_DIR environment variable to the base installation path or add -DCMSGeom_DIR to the cmake command")
  endif()
endif()
